version: "3"

services:
#####################################################################
# nginx
#####################################################################
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frspc_network


#####################################################################
# mysql
#####################################################################
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - frspc_network


#####################################################################
# tusd
#####################################################################
  tusd:
    container_name: tusd
    image: tusproject/tusd:latest
    command: -behind-proxy -disable-download -hooks-http http://localhost/api/cloud/hooks
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./tusd/data:/srv/tusd-data/data
    networks:
      - frspc_network
#####################################################################
# ollama
#####################################################################
  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    networks:
      - frspc_network





#####################################################################
# Next.js
#####################################################################
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}


    env_file:
      - .env
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - tusd
      - nginx
    networks:
      - frspc_network


#####################################################################
# Network
#####################################################################
networks:
  frspc_network:
    external: true
