version: "3"

services:
#####################################################################
# nginx
#####################################################################
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frspc_network


#####################################################################
# mysql
#####################################################################
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - frspc_network


#####################################################################
# mosquitto
#####################################################################
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.18
    ports:
      - "1883:1883" # Default MQTT port
      - "9001:9001" # Default MQTT port for WebSockets
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped
    networks:
      - frspc_network


#####################################################################
# tusd
#####################################################################
  tusd:
    container_name: tusd
    image: tusproject/tusd:latest
    restart: always
    ports:
      - 1080:1080
    volumes:
      - ./tusd:/data
    networks:
      - frspc_network


#####################################################################
# Next.js
#####################################################################
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}


    env_file:
      - .env
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - frspc_network


#####################################################################
# Network
#####################################################################
networks:
  frspc_network:
    external: true
